GOOGLE_API_KEY = "AIzaSyBz3nOl9UFqN3VyotAtqS-yS73fZc-XmzY"

[gsheets]
spreadsheet_url = "https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID/edit"

[credentials]
  [credentials.usernames.teacher]
  name = "Riya"
  password = "ldc12345"

[cookie]
expiry_days = 1
key = "some_signature_key"
name = "teacher_auth"